
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/bin/"
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/sbin/"
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/"
      - "C:/MinGW/bin/"
      - "C:/windows/system32/"
      - "C:/windows/"
      - "C:/windows/system32/wbem/"
      - "C:/windows/system32/WindowsPowershell/v1.0/"
      - "C:/Program Files/CMake/bin/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/bin/mingw32-make.exe.com"
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/bin/mingw32-make.exe"
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/sbin/mingw32-make.exe.com"
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/sbin/mingw32-make.exe"
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/mingw32-make.exe.com"
      - "Z:/home/satvara/Qt/6.7.3/mingw_64/mingw32-make.exe"
      - "C:/MinGW/bin/mingw32-make.exe.com"
      - "C:/MinGW/bin/mingw32-make.exe"
      - "C:/windows/system32/mingw32-make.exe.com"
      - "C:/windows/system32/mingw32-make.exe"
      - "C:/windows/mingw32-make.exe.com"
      - "C:/windows/mingw32-make.exe"
      - "C:/windows/system32/wbem/mingw32-make.exe.com"
      - "C:/windows/system32/wbem/mingw32-make.exe"
      - "C:/windows/system32/WindowsPowershell/v1.0/mingw32-make.exe.com"
      - "C:/windows/system32/WindowsPowershell/v1.0/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      CMAKE_PREFIX_PATH:
        - "Z:/home/satvara/Qt/6.7.3/mingw_64"
      ENV{PATH}:
        - "C:\\MinGW\\bin"
        - "C:\\windows\\system32"
        - "C:\\windows"
        - "C:\\windows\\system32\\wbem"
        - "C:\\windows\\system32\\WindowsPowershell\\v1.0"
        - "C:\\Program Files\\CMake\\bin"
...
